#name: Deploy to AKS
#
#on:
#  push:
#    branches:
#      - main
#
#jobs:
#  deploy:
#    runs-on: ubuntu-latest
#    environment: development
#
#    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
#    defaults:
#      run:
#        shell: bash
#
##    name: Set Terraform Variables
##    env:
##      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
##      ARM_CLIENT_ID: ${{secrets.ARM_CLIENT_ID}}
##      ARM_CLIENT_SECRET: ${{secrets.ARM_CLIENT_SECRET}}
##      ARM_SUBSCRIPTION_ID: ${{secrets.ARM_SUBSCRIPTION_ID}}
##      ARM_TENANT_ID: ${{secrets.ARM_TENANT_ID}} hello
#
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v3
#
#      - name: Set up JDK 17
#        uses: actions/setup-java@v3
#        with:
#          java-version: '17'
#          distribution: 'adopt'
#
#      # Install the latest version of Terraform CLI and configure the Terraform CLI configuration file with a Terraform Cloud user API token
#      - name: Setup Terraform
#        uses: hashicorp/setup-terraform@v1
#        with:
#          terraform_version: 1.0.0
#
#      - name: Azure login
#        uses: azure/login@v1
#        with:
#          creds: ${{ secrets.AZURE_CREDENTIALS }}
#
#      - name: Terraform Init
#        run: terraform init
#        working-directory: ./terraform
#
#      - name: Terraform Plan
#        run: terraform plan
#        working-directory: ./terraform
#
#      - name: Terraform Apply
#        run: terraform apply -auto-approve
#        working-directory: ./terraform
name: Deploy AKS using Terraform

on:
  push:
    branches:
      - master

jobs:
  terraform:
    name: Set Terraform Variables
    env:
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
      ARM_CLIENT_ID: ${{secrets.ARM_CLIENT_ID}}
      ARM_CLIENT_SECRET: ${{secrets.ARM_CLIENT_SECRET}}
      ARM_SUBSCRIPTION_ID: ${{secrets.ARM_SUBSCRIPTION_ID}}
      ARM_TENANT_ID: ${{secrets.ARM_TENANT_ID}}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.0

#      - name: Azure login
#        uses: azure/login@v1
#        with:
#          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Terraform Init
        run: terraform init
        working-directory: ./terraform

#      - name: Terraform Plan
#        run: terraform plan
#        working-directory: ./terraform

      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: ./terraform
